export const NOMES_FUNCIONARIOS = [
  "ADEMIR PINHEIRO DE SOUZA", "ADILSON FRANCISCO", "ADILSON FRANCISCO DOS SANTOS", "ADRIANO ROGERIO MOTA",
  "AGNALDO PAULO", "ALESSANDRO SELLI DE SOUZA", "ALEXANDRE SILVA DOS SANTOS", "ANA PAULA SILVA CORDEIRO",
  "ANDERSON BRANDI DAMAS", "ANDRE LUIS SANTOS NOGUEIRA", "ANTONIO CARLOS DA SILVA", "ANTONIO MARCOS DA CRUZ NEVES",
  "AUGUSTO STEPANAVISCIUS SIQUEIRA", "BENEDITO ANGELITO FRANCISCO", "BRENO EDUARDO SANTOS", "CACIO FERNANDO SILVA NUNES",
  "CAIO CESAR CAMOICO DOS SANTOS", "CLAUDECI BARROS DA SILVA", "CLAUDINEY DE SOUZA RODRIGUES", "CLEITON PELEGRINI FERNANDES",
  "CRISTIANO FERREIRA DE SOUZA SILVA", "CRISTIANO LEME", "DANIEL ANTONIO DEMETRIO", "DAVID PEREIRA DA SILVA",
  "DIEGO HENRIQUE ALVES SOARES", "DIEGO JOSE ALVES", "DIONIS PEREIRA MENDONCA", "DIVALDO JOSE DA SILVA",
  "EDIVALDO ALVES VIEIRA FILHO", "EDMAR JOSE DOS SANTOS", "ELIELTON DE OLIVEIRA COELHO", "ELTON BIBIANO DA SILVA",
  "ERMENSON APARECIDO RAMOS", "FABIO DE MELO BULHOES", "FELIPE BERTACINE", "FERNANDO CAMARGO DE SOUZA",
  "GIBSON ANTONIO GUEDES", "GISELE CRISTINA ROSA CORREA", "GISELE PEREIRA DE SOUZA", "IGOR FERNANDO FERREIRA FRANCISCO",
  "ITALO MATHEUS", "ISAIAS FERREIRA DA COSTA", "JALYSON ARAUJO DO PRADO", "JEFERSON DE JESUS MATTOS",
  "JOAO HENRIQUE MORAES HILARIO", "JOSE APARECIDO FERREIRA", "JOSE AUGUSTO DA SILVA", "JOSE COSTA DE OLIVEIRA JUNIOR",
  "JOSE ELIAS DE CAMARGO SILVA", "JOSEMAR BARROS LEITE DA SILVA", "JULIANO HENRIQUE DA SILVA SANTOS", "JULIANO PEREIRA FRAQUIM",
  "LEANDRO APARECIDO BULHOES", "LEANDRO DE SOUZA", "LUCAS DA SILVA RODRIGUES", "LUIS GUSTAVO ALVES BOTELHO",
  "LUIS VALENTIM ANDRE", "LUIZ CARLOS ALVES DE SOUZA", "LUIZ CARLOS DA SILVA", "MAICON APARECIDO FERMINO",
  "MARCIO DA SILVA GRILLO", "MARCIO JOSE DOS SANTOS", "MILTON RODRIGUES DE OLIVEIRA", "NATHAN GUSTAVO DE OLIVEIRA",
  "NELSON DE JESUS JUNIOR", "OSMAR ANTONIO FERRETI", "PATRICIA BARBOZA DE OLIVEIRA", "PATRICIA FERNANDA MORAIS SILVA",
  "PATRICK RODRIGUES DOS SANTOS SANTANA", "PAULO HENRIQUE DA SILVA SANTOS", "RAFAEL VINICIUS FOGACA NEVES", "REGINALDO DA SILVA DURAES",
  "RENAN APARECIDO PAES", "RENATO JUNIOR ROBERTO", "ROBER FELIX", "RONALDO EMANUEL DA COSTA",
  "SAMOEL PONTES SALOMAO", "SAMUEL DOS SANTOS FRANCO", "SIDINEI DA MATA MEDEIROS", "SIDNEI DE SANTANA",
  "THIAGO MARTINS DE MELLO", "VALDECIR CANEVARI", "VALDEIR JOSE MOREIRA JUNIOR", "VALDINEI NASCIMENTO DA SILVA",
  "VALDIR FERREIRA DA SILVA", "VANDERCI JUNIOR JERONIMO", "VICTOR AUGUSTO DA SILVA CARVALHO", "VINICIUS CARVALHO",
  "WANDERSON ALVES DA CRUZ", "WANDERSON WILLIAN SANTIAGO SANTOS", "WELLINGTON HENRIQUE DE MACEDO", "WILLIAN VIEIRA CORREA"
];

export const SUPERVISAO_OPTIONS = [
  { label: "NRD - Preparo e Plantio", email: "preparoeplantionrd@cocal.com.br" },
  { label: "NRD - Tratos Culturais", email: "tratosculturaisnrd@grupococal.onmicrosoft.com" },
  { label: "NRD - Herbicida", email: "herbicida.nrd@grupococal.onmicrosoft.com" },
  { label: "PPTA - Preparo e Plantio", email: "preparoeplantioppta@cocal.com.br" },
  { label: "PPTA - Tratos Culturais", email: "tratosculturaisppt@cocal.com.br" },
  { label: "PPTA - Herbicida", email: "herbicida.ppt@cocal.com.br" }
];

export const OPERACAO_OPTIONS = [
  "Quebra Lombo", "Cultivo", "Fertirrigação Localizada", "Fertirrigação Convencional",
  "Transporte de Torta", "Herbicida", "Capina Química", "Plantio Manual - MOR",
  "Plantio Mecanizado", "Colheita Muda", "Preparo de Solo", "Sistematização",
  "Corretivo Preparo", "Corretivo Tratos", "Cobrição", "Sulcação"
];

export const UNIDADE_OPTIONS = ["Paraguaçu Paulista", "Narandiba"];

export const SUPERVISORES = [
  { nome: "Igor Stevanato", email: "igor.stevanato@Cocal.com.br" },
  { nome: "Fabio Oliveira dos Santos", email: "fosantos@Cocal.com.br" },
  { nome: "João Gabriel Gonçalves Donha", email: "jdonha@cocal.com.br" },
  { nome: "Carlos Antonio Pretelli Junior", email: "carlos.pretelli@cocal.com.br" },
  { nome: "Supervisor 5", email: "supervisor5@empresa.com" },
  { nome: "Supervisor 6", email: "supervisor6@empresa.com" },
];
